---
- hosts: ubuntu
  become: yes
  tasks:
  - name: Adding the apt key for osquery
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
  - name: Adding repository
    apt_repository:
      repo: "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/xenial xenial main"
      state: present
  - name: installing using apt
    apt:
      name: osquery
      update_cache: yes

- hosts: windows
  tasks:
  - name: Install Chocolatey package manager and OSquery on windows targets
    win_chocolatey:
      name: osquery
      state: latest
  - name: Enable windows events for OSquery
    win_shell: C:\ProgramData\osquery\manage-osqueryd.ps1 -installWelManifest
